-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 15:31:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema integradora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema integradora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integradora` DEFAULT CHARACTER SET latin1 ;
USE `integradora` ;

-- -----------------------------------------------------
-- Table `integradora`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`bitacora` (
  `IdBitacora` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreTabla` VARCHAR(100) NULL DEFAULT NULL,
  `NombreCampo` VARCHAR(100) NULL DEFAULT NULL,
  `Fecha` DATETIME NULL DEFAULT NULL,
  `Usuario` VARCHAR(50) NULL DEFAULT NULL,
  `ValorAnterior` VARCHAR(255) NULL DEFAULT NULL,
  `ValorNuevo` VARCHAR(255) NULL DEFAULT NULL,
  `Accion` VARCHAR(20) NULL DEFAULT NULL,
  `IdCampo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdBitacora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`pais` (
  `IdPais` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`IdPais`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`estado` (
  `IdEstado` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(35) NULL DEFAULT NULL,
  `IdPais` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdEstado`),
  INDEX `fk_estado_pais` (`IdPais` ASC) VISIBLE,
  CONSTRAINT `fk_estado_pais`
    FOREIGN KEY (`IdPais`)
    REFERENCES `integradora`.`pais` (`IdPais`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`ruta` (
  `IdRuta` INT(11) NOT NULL AUTO_INCREMENT,
  `NomRuta` VARCHAR(50) NULL DEFAULT NULL,
  `Tipo` VARCHAR(50) NULL DEFAULT NULL,
  `Duracion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IdRuta`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`etapa` (
  `IdEtapa` INT(11) NOT NULL AUTO_INCREMENT,
  `NomEtapa` VARCHAR(50) NULL DEFAULT NULL,
  `Duracion` VARCHAR(50) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(50) NULL DEFAULT NULL,
  `IdRuta` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdEtapa`),
  INDEX `fk_etapa_ruta` (`IdRuta` ASC) VISIBLE,
  CONSTRAINT `fk_etapa_ruta`
    FOREIGN KEY (`IdRuta`)
    REFERENCES `integradora`.`ruta` (`IdRuta`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`usuario` (
  `NomUsuario` VARCHAR(50) NOT NULL,
  `Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `ApePat` VARCHAR(50) NULL DEFAULT NULL,
  `ApeMat` VARCHAR(50) NULL DEFAULT NULL,
  `FechaNac` DATE NULL DEFAULT NULL,
  `Correo` VARCHAR(50) NULL DEFAULT NULL,
  `Telefono` VARCHAR(15) NULL DEFAULT NULL,
  `Contrasenia` VARCHAR(50) NULL DEFAULT NULL,
  `IdPais` INT(11) NULL DEFAULT NULL,
  `IdEstado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`NomUsuario`),
  INDEX `fk_usuario_pais` (`IdPais` ASC) VISIBLE,
  INDEX `fk_usuario_estado` (`IdEstado` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_estado`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `integradora`.`estado` (`IdEstado`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_pais`
    FOREIGN KEY (`IdPais`)
    REFERENCES `integradora`.`pais` (`IdPais`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`historial` (
  `IdHistorial` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL DEFAULT NULL,
  `Costo` DOUBLE NULL DEFAULT NULL,
  `Pago` BIT(1) NULL DEFAULT NULL,
  `Descuento` VARCHAR(50) NULL DEFAULT NULL,
  `NomUsuario` VARCHAR(50) NULL DEFAULT NULL,
  `IdRuta` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdHistorial`),
  INDEX `fk_historial_nomusuario` (`NomUsuario` ASC) VISIBLE,
  INDEX `fk_historial_ruta` (`IdRuta` ASC) VISIBLE,
  CONSTRAINT `fk_historial_nomusuario`
    FOREIGN KEY (`NomUsuario`)
    REFERENCES `integradora`.`usuario` (`NomUsuario`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_historial_ruta`
    FOREIGN KEY (`IdRuta`)
    REFERENCES `integradora`.`ruta` (`IdRuta`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`promocion` (
  `PromocionQR` VARCHAR(767) NOT NULL,
  `Descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `Estatus` BIT(1) NULL DEFAULT NULL,
  `Descuento` VARCHAR(50) NULL DEFAULT NULL,
  `IdEtapa` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PromocionQR`),
  INDEX `fk_promocion_etapa` (`IdEtapa` ASC) VISIBLE,
  CONSTRAINT `fk_promocion_etapa`
    FOREIGN KEY (`IdEtapa`)
    REFERENCES `integradora`.`etapa` (`IdEtapa`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `integradora`.`usuariopromocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integradora`.`usuariopromocion` (
  `IdUsuarioPromocion` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL DEFAULT NULL,
  `Estatus` BIT(1) NULL DEFAULT NULL,
  `NomUsuario` VARCHAR(50) NULL DEFAULT NULL,
  `PromocionQR` VARCHAR(767) NULL DEFAULT NULL,
  PRIMARY KEY (`IdUsuarioPromocion`),
  INDEX `fk_usuariopromocion_nomusuario` (`NomUsuario` ASC) VISIBLE,
  INDEX `PromocionQR` (`PromocionQR` ASC) VISIBLE,
  CONSTRAINT `fk_usuariopromocion_nomusuario`
    FOREIGN KEY (`NomUsuario`)
    REFERENCES `integradora`.`usuario` (`NomUsuario`)
    ON UPDATE CASCADE,
  CONSTRAINT `usuariopromocion_ibfk_1`
    FOREIGN KEY (`PromocionQR`)
    REFERENCES `integradora`.`promocion` (`PromocionQR`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
